### ISSUE TITLE
where can I find the  "commons files" from theICTlab repository?

### ISSUE THREAD

**Issue by lelleMU** [charalambos/TensorClustering#1]
It says "You will also need to download our research lab's "commons files" from theICTlab repository". However, I juest can't find it anywhere. It really bothers me.
 Thanks very much!

**Comment by charalambos** [comment]
Hi,

You only need the Image.* and ImageProcessing.* files that are available in the P2C-clustering repo.

Best,

C.

**Comment by lelleMU** [comment]
Thank you professor. I saw many files needed in the CMake file, so I misunderstood. Thanks a lot for your reply!

**Comment by lelleMU** [comment]
> Hi,
> 
> You only need the Image.* and ImageProcessing.* files that are available in the P2C-clustering repo.
> 
> Best,
> 
> C.

I'm really sorry to bother you again. But I'm really confused because that in the main.txt I see it includes "GaborJet.h" and "weibullDistribution.h" which seem not available in he P2C-clustering repo. CMakeList seems to tell me that they are in the theICTlab repo.

**Comment by charalambos** [comment]
Try pulling the latest version. I've included the bare minimum to compile and run TC without depending on theICTlab repo.

**Comment by lelleMU** [comment]
Thank you a lot!&nbsp;
Wish you a good day.





------------------ Original ------------------
