### ISSUE TITLE
Full code source needed

### ISSUE THREAD

**Issue by abhishek31704** [charalambos/TensorClustering#2]
Hello,

 I read this excellent paper. 

The paper mentions that the code will be available. However, the code is only available for the first part i.e. Tensor clustering part. 

Where I can get the full code to see the reconstruction? (Global Boundary refinement). 

Regards,
Abhishek

**Comment by charalambos** [comment]
Hi,

The Global Boundary Refinement module is strongly coupled with a GUI application which includes other published and unpublished techniques. It will take quite some time for me to decouple it. I plan to do this but to be honest I am not sure when exactly.

The global boundary refinement improves the boundary points. The reconstruction though is already included in the GeometryExporter class. 

Best,

C.
