### ISSUE TITLE
´Please clarify CGAL and Boost version used

### ISSUE THREAD

**Issue by abhishek31704** [charalambos/TensorClustering#3]
Hello,

Tried building with multiple versions of CGAL but could not built. 

CGAL_LIBRARIES path is not set. This is due to the CGAL 5.0 has includes only version. 

Could you please clarify CGAL and Boost versions used in the project. ( I have used CGAL 5.0 , CGAL 5.2 and Boost 1.71 , 1.70 but not able to build)

**Comment by charalambos** [comment]
Hi, 

CGAL version 13 and Boost version 1.66.0 

Best,

C.

**Comment by abhishek31704** [comment]
Okay, Thanks. I am using ubuntu to install CGAL and Boost libraries. With version 13 you mean CGAL version 4.13?

**Comment by charalambos** [comment]
Sorry that was a typo, it should have been 12! The correct version is 4.12.2-lp152.2.14
