### ISSUE TITLE
Urgent Environment Info

### ISSUE THREAD

**Issue by abhishek31704** [charalambos/TensorClustering#4]
Hello, 

Sorry to contact you again but I need to get this code running in one or 2 days in my local windows or ubuntu virtual box machine to see reconstruction. The problem I am facing is CGAL Library Path not found and Boost Push Pop error with ( CGAL 5.2 and Boost 1.71). 
As there was no CBP file to use in Codeblock and looking at Cmake files I started with Ubuntu with Cmake and G++ for compilation.

 Just to be sure, which of these environments will work, or let me know the answer if it is not the right approach. 

I have some queries which need to be addressed urgently to make this running on my system.  
Environment:
1. What is preferred ( Windows, Ubuntu in VirtualBox, or Anaconda) is preferred? Which can support all available libraries to work together.  
2. Which Compiler(GCC, g++, MSVC), Cygwin, or MinGW?
3. Which Urban 3D open Dataset can be used to test this( I have the plan to run first on a small building dataset and later Toronto3D)

**Comment by abhishek31704** [comment]
Update: Resolved environment-related questions.

**Comment by charalambos** [comment]
Hi Abhishek,

Sorry for the delay. I'm glad you resolved the issue but I'll write this here in case anyone else has a similar question. 

The code was developed/tested on Opensuse Leap 42.3 and 15.0. I used Clion 2018.3, and gcc versions 7.x and 8.x. 

It takes as input an HDR XYZ map. You can use the StructurePointcloud module from my TPAMI 2013 paper; you can find the repo on my github account here:
https://github.com/charalambos/StructurePointcloud

It resamples an XYZ text file into the PFM format required by this module.

Hope this helps. 

Best,

C.
